# Production configuration for TeaTeach
spring:
  profiles:
    active: prod
  
  datasource:
    url: jdbc:mysql://localhost:3306/teateach?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:teateach}
    password: ${DB_PASSWORD:teateach123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

logging:
  level:
    org.bedrock: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  file:
    name: /opt/teateach/logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# File upload configuration
file:
  upload:
    path: /opt/teateach/uploads

# JWT configuration
jwt:
  secret: ${JWT_SECRET:your-very-secure-secret-key-for-production-change-this}
  expiration: 86400000  # 24 hours