---
apiVersion: v1
kind: Secret
metadata:
  name: teateach-backend-secrets
  namespace: teateach
  labels:
    app: teateach-backend
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  SPRING_DATASOURCE_USERNAME: dGVhdGVhY2g=  # teateach
  SPRING_DATASOURCE_PASSWORD: VGVhVGVhY2hEQjIwMjQ=  # TeaTeachDB2024
  
  # JWT Secret (base64 encoded)
  JWT_SECRET: VGVhVGVhY2hKV1RTZWNyZXRLZXkyMDI0VmVyeVNlY3VyZUFuZExvbmdTdHJpbmc=  # TeaTeachJWTSecretKey2024VerySecureAndLongString
  
  # Redis password (base64 encoded)
  SPRING_REDIS_PASSWORD: UmVkaXNQYXNzd29yZDIwMjQ=  # RedisPassword2024
  
  # MinIO credentials (base64 encoded)
  MINIO_ACCESS_KEY: dGVhdGVhY2htaW5pbw==  # teateachminio
  MINIO_SECRET_KEY: VGVhVGVhY2hNaW5pb1NlY3JldDIwMjQ=  # TeaTeachMinioSecret2024
  
  # Email credentials (base64 encoded)
  SPRING_MAIL_USERNAME: dGVhdGVhY2hAbWFpbC5jb20=  # teateach@mail.com
  SPRING_MAIL_PASSWORD: RW1haWxQYXNzd29yZDIwMjQ=  # EmailPassword2024
  
  # Encryption key for sensitive data (base64 encoded)
  ENCRYPTION_KEY: VGVhVGVhY2hFbmNyeXB0aW9uS2V5MjAyNA==  # TeaTeachEncryptionKey2024