from playwright.sync_api import Playwright, sync_playwright, expect
import re
import time


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(ignore_https_errors=True, record_har_mode="full", record_har_path="F:\\实训测试资料\\实训测试资料\\webrunner-x86_64-windows-20250616145951-16898d5b9\\filestorage\\recorder\\simulate\\teateach-add_course\\har_1751550696.har", service_workers="block")
    time.sleep(1)
    page = context.new_page()
    time.sleep(1)
    page.goto("http://172.22.46.32:8081/")
    time.sleep(1)
    page.goto("http://172.22.46.32:8081/login")
    time.sleep(1)
    page.get_by_placeholder("用户名").click()
    time.sleep(1)
    page.get_by_placeholder("用户名").fill("zhao")
    time.sleep(1)
    page.get_by_placeholder("密码").click()
    time.sleep(1)
    page.get_by_placeholder("密码").fill("123456")
    time.sleep(1)
    page.get_by_role("button", name="登录").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="任务").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="分析").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="任务").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="视频热图").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="题库").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="提交").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="视频热图").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="分析").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="视频热图").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="提交").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="题库").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="试卷").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="题库").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="提交").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="知识点").click()
    time.sleep(1)
    page.get_by_role("button", name="添加知识点").click()
    time.sleep(1)
    page.get_by_role("button", name="Close this dialog").click()
    time.sleep(1)
    page.get_by_role("button", name="从内容生成").click()
    time.sleep(1)
    page.get_by_role("dialog", name="从内容生成知识点").click()
    time.sleep(1)
    page.get_by_role("button", name="Close this dialog").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="资源").click()
    time.sleep(1)
    page.get_by_role("button", name="上传资源").click()
    time.sleep(1)
    page.get_by_text("资源名称描述文件将文件拖拽到此处或 点击上传支持的格式： PDF, DOCX, PPTX, MP4, JPG, PNG, TXT").click()
    time.sleep(1)
    page.get_by_placeholder("输入资源名称").click()
    time.sleep(1)
    page.get_by_placeholder("输入资源名称").fill("")
    time.sleep(1)
    page.get_by_role("button", name="Close this dialog").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="任务").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="课程").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="任务").click()
    time.sleep(1)
    page.get_by_role("cell", name="Python进阶课程设计").get_by_text("Python进阶课程设计").click()
    time.sleep(1)
    page.get_by_role("cell", name="python进阶学习").get_by_role("img").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="分析").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="视频热图").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="提交").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="题库").click()
    time.sleep(1)
    page.get_by_role("menuitem", name="试卷").click()
    time.sleep(1)
    page.get_by_role("button", name="生成试卷").click()
    time.sleep(1)
    page.get_by_placeholder("请输入试卷名称").click()
    time.sleep(1)
    page.get_by_placeholder("请输入试卷名称").fill("")
    time.sleep(1)
    page.get_by_role("button", name="×").click()
    time.sleep(1)
    page.get_by_role("button", name="生成试卷").click()
    time.sleep(1)
    page.get_by_placeholder("请输入试卷名称").click()
    time.sleep(1)
    page.get_by_placeholder("请输入试卷名称").fill("python基础测试")
    time.sleep(1)
    page.locator("form div").filter(has_text="试卷名称 *课程 *选择课程Matlab数学模型设计C++程序设计Python进阶课程设计高等数学线性代数概率论与数理统计数值分析大学英语人工智能基础教育学电子").get_by_role("combobox").select_option("3")
    time.sleep(1)
    page.locator("div").filter(has_text=re.compile(r"^生成方式 \*选择方式随机选择按知识点按难度平衡分布$")).get_by_role("combobox").select_option("BY_KNOWLEDGE_POINT")
    time.sleep(1)
    page.get_by_placeholder("题目数量").click()
    time.sleep(1)
    page.get_by_text("时长（分钟）总分").click()
    time.sleep(1)
    page.get_by_placeholder("总分").click()
    time.sleep(1)
    page.get_by_placeholder("总分").fill("10")
    time.sleep(1)
    page.get_by_text("单选题").click()
    time.sleep(1)
    page.get_by_text("简答题").click()
    time.sleep(1)
    page.get_by_role("button", name="从知识图谱选择").click()
    time.sleep(1)
    page.locator("canvas").click(position={"x":621,"y":243})
    time.sleep(1)
    page.get_by_role("button", name="Fit to Screen").click()
    time.sleep(1)
    page.locator("div").filter(has_text=re.compile(r"^选择知识点×$")).get_by_role("button", name="×").click()
    time.sleep(1)
    page.get_by_role("button", name="预览题目").click()
    time.sleep(1)
    page.locator("form").get_by_role("button", name="生成试卷").click()
    page.close()

    # ---------------------
    time.sleep(2)
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
